# Generated by Django 5.1 on 2026-02-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='account_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
