# Generated by Django 5.1 on 2026-02-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_details', '0002_member_account_status_alter_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='emp_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
