# Generated by Django 5.1 on 2026-04-06 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_details', '0004_attendance_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='country',
            field=models.ForeignKey(default=1, help_text='Invoice country', on_delete=django.db.models.deletion.PROTECT, to='bio_details.country'),
        ),
    ]
