# Generated by Django 6.0.2 on 2026-02-27 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio_details', '0007_order_alter_brand_id_alter_cart_id_alter_cartitem_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='purchase_limit',
        ),
    ]
