# Generated by Django 5.1 on 2026-04-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_details', '0009_remove_member_user_alter_attendance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
