# Generated by Django 5.1 on 2026-03-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_details', '0011_remove_order_price_remove_order_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
