# Generated by Django 5.1 on 2026-04-10 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio_details', '0012_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='member',
            table='bio_details_member',
        ),
    ]
