# Generated by Django 6.0.2 on 2026-03-24 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio_details', '0016_remove_invoice_delivery_status_alter_brand_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='terms_conditions',
        ),
    ]
