# Generated by Django 5.1 on 2026-04-13 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio_details', '0017_alter_attendance_unique_together_and_more'),
    ]

    operations = [
    ]
