# Generated by Django 6.0.2 on 2026-03-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_details', '0017_remove_invoice_terms_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='terms_conditions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
