# Generated by Django 5.1 on 2026-03-30 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_details', '0021_currency_alter_brand_id_alter_cart_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.ForeignKey(default=1, help_text='Order currency', on_delete=django.db.models.deletion.PROTECT, to='bio_details.currency'),
        ),
    ]
