# Generated by Django 6.0.2 on 2026-04-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_details', '0026_alter_productreview_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='technical_comment',
            field=models.TextField(default='timezone.now '),
            preserve_default=False,
        ),
    ]
