# Generated by Django 6.0.2 on 2026-04-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_details', '0027_productreview_technical_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='technical_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
