# Generated by Django 6.0.2 on 2026-04-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_details', '0031_remove_productreview_technical_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('complete', 'Complete')], default='open', max_length=15),
        ),
    ]
