from django.urls import path
from . import views

app_name = 'bio_details'

urlpatterns = [
    path('form/', views.members, name='members'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('', views.login_page, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('table/', views.table, name='table'),
    path('delete/<int:id>/', views.delete_member, name='delete_member'),
    path('rewrite/<str:emp_id>/', views.rewrite_member, name='rewrite_member'),
    path('product/', views.product_management, name='product_management'),
    path('product_form/', views.product_form, name='product_form'),
    path('rewrite_form/<str:product_id>/', views.product_rewrite, name='product_rewrite'),
    path('product_purchase/', views.product_view, name='product_view'),
    path('shop/<str:product_id>/', views.shop_detail, name='shop_detail'),
    path('product-delete/<str:product_id>/', views.delete_product, name='delete_product'),
    path('search-products/', views.search_products, name='search_products'),
    path('cart/', views.cart_view, name='cart_view'),
    path('add-to-cart/<str:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('update-cart/<int:item_id>/', views.update_cart_item, name='update_cart_item'),
    path('remove-cart/<int:item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('apply-discount/', views.apply_discount, name='apply_discount'),
    path('checkout/', views.checkout, name='checkout'),
    path('order/', views.order_view, name='order'),
    path('update-invoice-item/<int:item_id>/', views.update_invoice_item, name='update_invoice_item'),
    path('get-product-stock/', views.get_product_stock, name='get_product_stock'),
    path('update-invoice-item-qty/<int:item_id>/', views.update_invoice_item_qty, name='update_invoice_item_qty'),
    path('invoice/', views.invoice_view, name='invoice'),
    path('invoice/<int:order_id>/', views.invoice_view, name='invoice_detail'),
    path('place-order/', views.place_order, name='place_order'),
    path('add-product-to-invoice/<int:order_id>/', views.add_product_to_invoice, name='add_product_to_invoice'),
    path('add-product-ajax/<int:order_id>/', views.add_product_to_invoice_ajax, name='add_product_ajax'),
    path('cancel-order/', views.cancel_order, name='cancel_order'),
    path('remove-invoice-item/<int:item_id>/', views.remove_invoice_item, name='remove_invoice_item'),
    path('update-payment-method/<int:invoice_id>/', views.update_payment_method, name='update_payment_method'),
    path('invoice2/<int:order_id>/', views.invoice2_view, name='invoice2_detail'),
    path('my-orders/', views.my_orders, name='my_orders'),
    path('delete-order/<int:order_id>/', views.delete_order, name='delete_order'),
    path('save-terms-conditions/', views.save_terms_conditions, name='save_terms_conditions'),
    path('get-order-items/<int:order_id>/', views.get_order_items, name='get_order_items'),
    path('print-invoice/<int:order_id>/', views.print_invoice, name='print_invoice'),
    path('my-profile/', views.my_profile, name='my_profile'),
    path('convert-currency/', views.convert_product_currency, name='convert_currency'),
    path('save-country-selection/', views.save_country_selection, name='save_country_selection'),
    path('save-currency-selection/', views.save_currency_selection, name='save_currency_selection'),
    path('attendance/', views.attendance, name='attendance'),
    path('my-applications/', views.my_applications, name='my_applications'),
    path('manage-leave-applications/', views.manage_leave_applications, name='manage_leave_applications'),
]
